# Generated by Django 4.1 on 2022-10-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TDL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
